config/routes.rb
Rails.application.routes.draw do
 
	root 'people#index'

	resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
  	@people = Person.all
  end

  def show
  	@people = Person.find(params[:id])
  end

  def new
  	@people = Person.new
  end

  def edit
		@people = Person.find(params[:id])
  end

  def create
  	@people = Person.new(params[:id])

  	if @people.save
      redirect_to person_path(@people)
    else
      render :new
  	end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsModels</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<h1>Edit</h1>
<p>Find me in app/views/people/edit.html.erb</p>

app/views/people/index.html.erb
<h1>List of People</h1>

<% @people.freeze do |people| %>
  <blockquote>
    <h1 ><%= @people.name %></h1>
    <h2><%= @people.age %></h2>
    <!--<i> ID: <%= task.id %></i>-->
    <br /><br />
    <%= link_to 'View Person', person_path(person) %>
    <%= link_to 'Edit Person', edit_person_path(person) %>
    <%= link_to 'Complete Person', @people, method: :delete %>

  </blockquote>
  <hr />
<% end %>
<%= link_to 'Create Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= form_for @people do |f| %>
  <%= f.text_field :name, placeholder: 'Name' %>
  <br />
  <%= f.text_field :age, placeholder: 'Age' %>
  <br />
  <%= f.text_field :hair_color, placeholder: 'Hair color' %>
  <br />
  <%= f.text_field :eye_color, placeholder: 'Eye color' %>
  <br />
  <%= f.text_field :gender, placeholder: 'Gender' %>
  <br />
  <%= f.label :alive %>
  <%= f.check_box :alive %>
  <br />
  <%= f.submit %>
<% end %>

app/views/people/show.html.erb
<h1>New Person!</h1>

<h2><%= @people.name %></h2>